### PR TITLE
Add lesshint

### PR DESCRIPTION
**Pull request by jwilsson**

### CODE REVIEW

**Comment by seven-phases-max** [comment]
Thanks but `lesshint` is not quite a Less plugin, but a separate tool. So I think you'll need to find some other section in the docs to put it to.

**Comment by jwilsson** [comment]
Ah, didn't read the list careful enough, sorry about that.

I was thinking, are you guys opposed to adding a new section/subsection named "Third Party Tools" or something along those lines?

**Comment by seven-phases-max** [comment]
>are you guys opposed to adding a new section/subsection named "Third Party Tools" or something along those lines?

Not at all (I guess). Though if it's going to be a new section it's probably better to start with more than one link :)

**Comment by jwilsson** [comment]
Well, one's gotta start somewhere ;) 

But if you guys wanna wait we'll obviously do that.

**Comment by SomMeri** [comment]
I merged that in and if someone think that new section is better idea, I will gladly merge that change in too. I just think that small entry like this is better then none at all, so I merge it in rather then have it forgotten for next months :).

**Pull request merged**
