### PR TITLE
Add sass2less as a less preprocessor plugin

### PR DESCRIPTION
**Pull request by mediafreakch**
Hi,

I created a less-plugin that lets you convert `.scss` files to `.less` or import SASS files directly into your LESS files. Would you be so kind to link it in your docs?

Edi

### CODE REVIEW

**Comment by seven-phases-max** [comment]
Thanks!

**Comment by matthew-dean** [comment]
Holy crap, does this work?? Can it convert Bootstrap 4?

**Comment by mediafreakch** [comment]
@matthew-dean I just tested it on Bootstrap 4 and apparently there are some uncovered conversions. I'll have a look and let you know as soon as it works.

It definitely already works on `material-design-lite`.

**Comment by mediafreakch** [comment]
Bootstrap 4 is using some quite advanced SASS functions that I have to look into first. You can keep track or support me here: https://github.com/mediafreakch/less-plugin-sass2less/issues/1

**Pull request merged**
