### PR TITLE
Active items should not have a link

### PR DESCRIPTION
**Pull request by bassjobsen**
should also close https://github.com/less/less-docs/issues/199

### CODE REVIEW

**Comment by szepeviktor** [comment]
When will it be online?

**Comment by lukeapage** [comment]
Someone needs to push a build to the repo. I have no computer for a week.
Other people have access and should feel free to do it.

**Comment by SomMeri** [comment]
@lukeapage How is it done? I have both computer and time to do it, but I do not know what needs to be done nor whether I have right to do so.

**Comment by lukeapage** [comment]
You do grunt to build to _lesscss.org folder (or some folder like it), then
overwrite that into the lesscss.org repo and push..

**Comment by lukeapage** [comment]
Sorry the repo/ folder name is https://github.com/less/less.github.io

Also i forgot to push my change to increment the version - change the
version in here :
https://github.com/less/less-docs/blob/master/data/less.json before
building.

Thanks! You should have permission.

**Comment by SomMeri** [comment]
It is done and up :)

**Comment by lukeapage** [comment]
Thanks!

**Pull request merged**
