### PR TITLE
add `isruleset` function

### PR DESCRIPTION
**Pull request by Justineo**

### CODE REVIEW

**Comment by seven-phases-max** [comment]
The only remark: "detached" should not be used there ("detached ruleset"  is an internal/code-name of the whole feature (not the particular type of the value of the tested variable)). So it's just confusing in this context.

**Comment by Justineo** [comment]
I thought about that too but I choose to use this term because the current docs [already use it](http://lesscss.org/features/#detached-rulesets-feature) to introduce the related features. So maybe that should be changed too?

**Comment by seven-phases-max** [comment]
>So maybe that should be changed too?

Yes, this (ideally) should be changed too (eventually). In fact [initially](https://github.com/less/less-docs/blob/bb20bd763b14294a65a68a2aef75b4ff93552f64/content/features/detached-rulesets.md) it did not used that "code-name" too.

**Comment by seven-phases-max** [comment]
Thanks!

**Pull request merged**
