### PR TITLE
Update math-functions.md

### PR DESCRIPTION
**Pull request by cduivis**
Percentage does not return a string, but a number.
```less
@percentage : percentage(1/3);
isnumber(@percentage); // outputs true
isstring(@percentage); // outputs false
```

### CODE REVIEW

**Comment by matthew-dean** [comment]
@cduivis Hmm....it's a bit more complicated than this change. What `percentage` actually returns is a _unit_ (a value with unit characters), not a number or string, with `%` being somewhat like `px`. In Less, units can be operated on, and they are serialized to string values. The `isnumber` function returns true for any unit. You can test that it's actually a unit with `isunit(percentage(1/3), %);`

So the documentation should say is that `percentage` returns a percentage unit.

**Comment by seven-phases-max** [comment]
@matthew-dean
I'd say in Less a *Number* (a type which is internally weirdly named "Dimension") is "a numeric value with an optional unit". (Because a unit *is* an internal part of the Dimension type. Internally it's even more complicated as the numeric part of the Dimension also consists of numerator/denominator parts, but that's another story).

So yes, I'd definitely say that a value like `1%` is a *Number* and nothing but a Number in *Less* (i.e. don't get confused: it's not the same Number type as in e.g. JS or C#), thus I believe @cduivis (as well as `isnumber`) is correct and current `percentage` description is wrong.

>So what the documentation should say is that percentage returns a (percentage) unit.

No. A Unit is `%` itself, but it's not what `percentage` returns.

**Comment by seven-phases-max** [comment]
P.S. Well, it may look like a matter of personal definitions - but it's just how most of functions documentation held it before. We don't have any specific "Types" reference so "what type does this value belongs to?" is basically a matter of all those `is*` functions *and* other functions "returns" descriptions (not always consistent but still less or more following the same style: i.e. `"number" == Dimension`).

**Comment by matthew-dean** [comment]
@seven-phases-max You're right that it's a Dimension, I misspoke. It's not weirdly named. It's actually precisely what the CSS spec calls it -- https://drafts.csswg.org/css-values-4/#dimension. Interestingly, a dimension actually excludes percentages, but they all fall under the category of "numeric data types".

So, no, it's not a number and it's not a string. It's what I said -- a percentage. The fact that `isnumber` returns `true` is okay, I suppose, since it's in the `numeric data type` category, and because of how Less operations work.

My only concern is that changing the documentation to say it's a number could just lead to confusion on a different side e.g. someone believing that `50%` literally represents the numeric value `0.5`, which it doesn't. It represents the value `50[unit]`, with `[unit]` being `%`, and `50` being the actual numeric value. So it doesn't _return_ a number but it can be _cast_ or _used_ as a number in operations.

**Comment by seven-phases-max** [comment]
@matthew-dean
>It's actually precisely what the CSS spec calls it

True (I guess that's why it's named like that in Less sources) - still weird... 

>e.g. someone believing that 50% literally represents the numeric value 0.5

I see, well, I hope it's too minor thing to bother to bring in a complicated explanation of how `%` is specific... For that kind of coonfusion we'll always (re)open another thread with all heavy artillery in.

**Pull request merged**
