### PR TITLE
Add svelte-preprocess to Tools section

### PR DESCRIPTION
**Pull request by benmccann**
There didn't seem to be a good existing section for this, so I made a new one. Do I need to link it from anywhere? I didn't see `editors-and-plugins` referenced anywhere, so I was assuming it'd be included automatically

### CODE REVIEW

**Comment by matthew-dean** [comment]
Yeah, you're right, I don't see this directly on https://lesscss.org/tools/. It would be great to include things like `less-loader` and `rollup-plugin-less` etc, basically Less plugins for other tools. I wonder if there's a better / more-clarifying name for that than "Preprocessors". Because it's not really a separate pre-processor, it's basically a tooling plugin that connects to an existing pre-processor (Less).

**Comment by matthew-dean** [comment]
Maybe we could repurpose / rename the "Node.js Compilers" section? Because, again, those happen to be compilers that run in Node, yes, but that list includes Grunt / Gulp / Assemble tooling plugins, which is what this would fall under.

**Comment by benmccann** [comment]
I just updated this as suggested. Sorry for having lost track of this

Btw, I removed `assemble-less` because it hasn't been touched since 2014 and `autoless` because it says it's no longer maintained and has been archived

**Review by iChenLei — APPROVED** [review]
LGTM

**Pull request merged**
