### PR TITLE
feat(docs): added fomantic-ui to framework list

### PR DESCRIPTION
**Pull request by lubber-de**
## Description

Fomantic-UI took over active development of SUI in 2018 and since then made use of LESS features for dynamic compilation of many classes for colors or sizing, which SUI still has hardcoded.

### CODE REVIEW

**Review by iChenLei — CHANGES_REQUESTED** [review]
I can access https://fomantic-ui.com , but https://www.fomantic-ui.com  is not working. Please check the URL.

**Review by lubber-de — COMMENTED** [review]
fix(docs): removed subdomain from fomantic-ui

**Comment by lubber-de** [comment]
I removed the subdomain (this is the official way and everywhere else promoted link to access the website (without www).
However, i have spoken to the domain admin to also support www subdomain. Thanks for the hint

**Review by iChenLei — APPROVED** [review]

**Comment by iChenLei** [comment]
Looks great, thank you.

**Pull request merged**
