### PR TITLE
Opinionated comma addition

### PR DESCRIPTION
**Pull request by su-narthur**

### CODE REVIEW

**Comment by matthew-dean** [comment]
Oxford comma, I like it lol.

**Comment by seven-phases-max** [comment]
I'd say this is really looks weird in *any* langauge (those academist are simply out of really and start to invent their own noone's understood language).

**Comment by Synchro** [comment]
- https://www.reddit.com/r/funny/comments/ki8cp/grammar_is_important_kids/
- https://www.buzzfeed.com/adamdavis/the-oxford-comma-is-extremely-important-and-everyone-should?utm_term=.uamWzdXP6j#.kePaKBxkNd

**Comment by seven-phases-max** [comment]
Yep, honestly I did not know this one of those Mac vs. PC holywars.... So... the question is - why this particular phrase is decided to use Mac? Do we have these solving nothing commas anywere else in the docs?

**Comment by matthew-dean** [comment]
o_O What does this have to do with Mac vs. PC?

**Comment by seven-phases-max** [comment]
This particular "Oxford Comma" rule is a subject of the Holy War similar to Mac-vs-PC,  Windows-vs-Linux etc. As clearly shown in the first link by @Synchro. The second link just one of those "You *should* because *I* do" articles (listing all the reasons for it and being mute on everything against it). Obviously one can find zillion articles doing the same for both sides of the war.

So... since 
* we did not have this rule marked as an obligatory for the docs
* we do not use such comma anywhere else in the docs
 here's the question: why this particular totally unambiguity list gets it?

**Comment by matthew-dean** [comment]
...

An Oxford comma is less ambiguous. Documentation should be as unambiguous as possible. I don't see why this would be a controversial change. The arguments against usually revolve around, "I don't personally see such lists as ambiguous," but no one claims an Oxford comma is _more_ ambiguous, or makes a list harder to read. Simply that the mental insertion of a comma is not over-exerting for that particular individual.

But, since the addition harms no readability in documentation, and the omission harms readability for some (however slight) it seems to me the onus would be on an argument to omit it.

Personally, as a programmer, a list that looks like `[1, 2, 3, 4 5]` kinda looks odd, so for docs targeting programmers, it makes more sense to me.

> here's the question: why this particular totally unambiguous list gets it?

You are correct. A more correct PR should have included corrections for all lists for consistency. I don't think we need to explicitly state which grammar style guide we're using for docs. Obviously different PRs by different people might have slight grammar style variations, and I've corrected a lot of grammar (unrelated to lists) in the 3.x doc revisions.

**Comment by seven-phases-max** [comment]
The primary reason the people argue against is aesthetics (no, Natural Language Aesthetics actually) . It's OK for you to like such comma if they taught you like this, but don't expect others to accept and follow accept such artificial rule forced into a natural language (after all comma usage has been polished for centuries, and it's not for some guys (like those behind this rule), who continuously fail to produce an unambiguous lists and then trying to hide their faults by forcing synthesized dumb punctuation on others, to decide). We may keep throwing all these Holy War args at each other but this is pointless - we can both just reread https://en.wikipedia.org/wiki/Serial_comma - they are all there.

>Personally, as a programmer, a list that looks like [1, 2, 3, 4 5] kinda looks odd, so for docs targeting programmers, it makes more sense to me.

You know yourself this is a screwed example... neither [1, 2, 3, 4 or 5] nor [1, 2, 3, 4 and 5] are [1, 2, 3, 4 5].

>Obviously different PRs by different people might have slight grammar style variations

Yes, and then I would not even bother if I see such comma in some sentence ("A misprint", Max thought). But this PR is just... pheeeew...

**Comment by su-narthur** [comment]
Sorry, @seven-phases-max. I certainly wasn't attempting to start a holy war. You'll notice I included *opinionated* in the PR title--that was for a reason. Maybe you guys want to have a style guide, maybe not--you guys will have to work that out. I do hope that you all don't make a habit of spending all this breath on arguing over a one-character PR request.

Who knows--maybe you all don't want one-character PRs, period? That's your call, too, I guess. I think it's a valuable thing to let your community suggest corrections on a whim; and, at times, they might be a little opinionated. ;)

**Comment by matthew-dean** [comment]
This just seems like such small beans I just don't understand why it's even a topic of discussion. There's so many other better places to put energy into Less.

To me, this was literally:

Someone: "Imma put a comma here."

Me: "Great! Someone is invested in Less documentation." -> Merge

The other options were:

1. Waste time discussing if a comma should be merged.
2. Waste time discussing what said comma means in the larger scheme of grammar, as is applied to Less documentation.

We have now thoroughly covered 1 and 2. I really don't care one way or the other which one is adopted for Less documentation. It's so unimportant in the scheme of things to care about in the documentation that it's just not worth the time.

What's more important to me as far as maintaining documentation is that people care AT ALL about documentation, and I figured maybe this was the first tiny PR of this particular contributor who, when encouraged, might make other documentation or Less.js contributions.

If there is some need to pick some style standard, then that usually comes down to an editor just arbitrarily deciding, and that would probably be whomever is most invested in updating documentation. Grammar is not something to open source.

**Comment by matthew-dean** [comment]
Sorry if that came across as dismissive. If someone cares about this issue, that's ok.

**Pull request merged**
