### PR TITLE
Remove disfunct online compilers

### PR DESCRIPTION
**Pull request by oBusk**
less2css.org - Ad-riddled domain-squatter
dopefly.com/less-converter - Cannot parse any input
lessphp.gpeasy.com/demo - Leads to no page with no input/output field
precess - 502
ILess - Can't be reached

### CODE REVIEW

**Comment by seven-phases-max** [comment]
Just in case `less2css` moved [here](http://lesscss.org/less-preview/).

**Comment by seven-phases-max** [comment]
Thanks!

**Comment by oBusk** [comment]
Should i readd `less2css` with the correct URL?

**Comment by seven-phases-max** [comment]
@oBusk I did in https://github.com/less/less-docs/commit/ca783c9dab2e34c53956914d8768e29bdaeed490.

**Pull request merged**
