### PR TITLE
fix: 文案错误修复

### PR DESCRIPTION
**Pull request by webxmsj**

### CODE REVIEW

**Comment by iChenLei** [comment]
I think this expression is correct.

**Comment by iChenLei** [comment]
If you have any questions, we can re-open this pr if needed.

**Comment by webxmsj** [comment]
Using Lessc to compile the sample less file into a CSS file, the result is the opposite of what the documentation describes

**Comment by iChenLei** [comment]
Test on local machine, works as expected.
```bash
$ cat ./test.less
.my-mixin {
    color: black;
}

.my-other-mixin() {
    background: white;
}

.class {
    .my-mixin();
    .my-other-mixin();
}

$ ./node_modules/.bin/lessc test.less
.my-mixin {
  color: black;
}
.class {
  color: black;
  background: white;
}


$ ./node_modules/.bin/lessc --version
lessc 4.1.2 (Less Compiler) [JavaScript]
```

**Comment by webxmsj** [comment]
Thank you. Sorry about the mistake

**Pull request closed without merging**
