### PR TITLE
Update List Function Docs

### PR DESCRIPTION
**Pull request by puranjayjain**
To Specify correction in docs to match the correctly mention integers (which can be starting from 0) to positive integers which start from 1

### CODE REVIEW

**Comment by seven-phases-max** [comment]
I'd rather use "starting from 1" (it's omitted simply because index base is inherited from CSS). "Positive" sounds correct, but to be honest, even me would not connect it to "not starting from 0" at quick glance.

**Comment by puranjayjain** [comment]
@seven-phases-max shall I make appropriate changes to it then ? starting from 1

**Comment by seven-phases-max** [comment]
Yes, sure. Could something like
* `index` - a integer that specifies a 1-based position of a list element to return. 
* Remarks: the index numbering starts at 1.
* Remarks: The index of the first element is 1.
or somewhat in between.

P.S. Personally I used ["A one-base index of the element to return"](https://github.com/seven-phases-max/less-plugin-lists/blob/master/docs/ref.md#at) for the same thing, but I'm never sure about a better novice-friendly wording).

**Comment by puranjayjain** [comment]
@seven-phases-max great suggestion I'll work something out for the entire docs on Monday

**Comment by matthew-dean** [comment]
Is this going to be updated?

**Pull request closed without merging**
