### PR TITLE
SECURITY alert! less2css.org is malicious

### PR DESCRIPTION
**Pull request by seangates**
Please consider fixing this ASAP.

### CODE REVIEW

**Comment by seven-phases-max** [comment]
Well, as you can't see the link is already fixed in the master. As for the title, there's no such thing as "lesscss.org/preview" online compiler (it's basically a temporary hosting for an outdated tool anyway), so I'd rather suggest to remove the whole thing all together untill we have something better.

**Comment by seven-phases-max** [comment]
Either way I did a quick manual fix right in the docs "binaries": https://github.com/less/less.github.io/commit/fee2176df03f725a2b94860d888472f370c1e0b3.

**Comment by matthew-dean** [comment]
Thanks @seven-phases-max!

**Comment by seangates** [comment]
So ... if it's fixed why did it take me to a malicious website?

**Comment by matthew-dean** [comment]
@seangates @seven-phases-max I've pushed to Github.

**Pull request closed without merging**
